"""add is_final_attempt to usage_records

Revision ID: 7ead1fbc7c58
Revises: 8d2dcb772e99
Create Date: 2026-09-23 15:43:12.914229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ead1fbc7c58'
down_revision: Union[str, Sequence[str], None] = '8d2dcb772e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('is_final_attempt', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'is_final_attempt')
    # ### end Alembic commands ###
